spring.datasource.url=jdbc:mysql://localhost/flm_employee
spring.datasource.username=root
spring.datasource.password=thiru
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8181
server.servlet.context-path=/emp
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true